[general]
start_key = 'esc'
stop_key = 'q'
delay = 0.0001

[reaction_time]
nb_clicks = 5
click_pause = 1
auto_continue = true
screenshot_width = 3
screenshot_height = 3

[target_aimer]
nb_targets = 30
target_size = 50
quantile = 0.5
click_pause = 0.015
